### ISSUE TITLE
question about transform

### ISSUE THREAD

**Issue by lymanlai** [petervmeijgaard/vue-2.0-boilerplate#10]
Hi @petervmeijgaard 
is there a problem that in server site just return camelCased json data?
so, we do not need transform stuff here?

thx

**Comment by petervmeijgaard** [comment]
Hi @lymanlai, it is a best practice to return snake_cased values in an API. As you can see here for the Twitter API: https://dev.twitter.com/rest/reference/get/search/tweets

**Comment by petervmeijgaard** [comment]
But yeah, if you want to return camelCased values, you are free in doing so and you can strip the transformers completely. I just give an example how to deal with traditional RESTfull APIs.

**Comment by lymanlai** [comment]
cool thx
