### ISSUE TITLE
Set history mode on router

### ISSUE THREAD

**Issue by m33ch** [petervmeijgaard/vue-2.0-boilerplate#11]
Hi all,

thank you @petervmeijgaard for this package.

Hi try to enable history mode on <code>bootstrap.js</code> like this :

```
export const router = new VueRouter({
  mode: 'history',
  routes: [routes],
});
```

no error on webpack, but on browser console i got this error 
```
[vue-router] "path" is required in a route configuration
```
I try to set <code>root</code> parameter on <code>VueRouter</code> constructor but error remain.

Thank you very much!

**Comment by petervmeijgaard** [comment]
Try this 😄:

```
export const router = new VueRouter({
  mode: 'history',
  routes,
});
```

Instead of `routes: [routes]`, it will compile to `routes: routes`.

**Comment by m33ch** [comment]
Oh! Thankyou @petervmeijgaard !
