### ISSUE TITLE
Redirect is not a function

### ISSUE THREAD

**Issue by harrysbaraini** [petervmeijgaard/vue-2.0-boilerplate#13]
I'm getting a 'Redirect is not a function' in the bootstrap.js file, on router.beforeEach guard.

I have read the Vue Router doc (http://router.vuejs.org/en/advanced/navigation-guards.html) and it says that global guards has the following signature:

```
router.beforeEach((to, from, next) => {
  // ...
})
```

So to redirect we have to use the next argument.

**Comment by petervmeijgaard** [comment]
Fixed in:
https://github.com/petervmeijgaard/vue-2.0-boilerplate/commit/fbe087c81b7bc1b71f01f51dfa41e26f5d7f6dc9
