### ISSUE TITLE
Set header to 'null' in logout breaks future xhr requests

### ISSUE THREAD

**Issue by wimva** [petervmeijgaard/vue-2.0-boilerplate#15]
In app/store/modules/auth/mutations.js on line 25:
`Vue.http.headers.common.Authorization = null;`

When this is fired and future xhr request are made, these request will fail because of the error: `null is not an object (evaluating 'str.replace')` in the trim function of `vue-resource`

It is fixed by replacing that line by:
`Vue.http.headers.common.Authorization = '';`

**Comment by petervmeijgaard** [comment]
Thanks for the headsup! Will fix it now...
