### ISSUE TITLE
Consider Removing vue-resource From This Boilerplate

### ISSUE THREAD

**Issue by knpwrs** [petervmeijgaard/vue-2.0-boilerplate#18]
`vue-resource` is being retired: https://medium.com/the-vue-point/retiring-vue-resource-871a82880af4#.xk0b5eimw

Note that this is different from deprecated. It just isn't an official recommendation anymore. To quote the reasoning:

> 1. Unlike routing and state-management, ajax is not a problem domain that requires deep integration with Vue core. A pure 3rd-party solution can solve the problem equally well in most cases.
> 1. There are great 3rd party ajax libraries that solve the same problem, are more actively improved/maintained, and designed to be universal/isomorphic (works in both Node and Browsers, which is important for Vue 2.0 with its server-side rendering usage).
> 1. Given (1) and (2), it’s obvious that we are duplicating the effort and bringing in unnecessary maintenance burdens by keeping vue-resource’s current status. The time we spend on resolving vue-resource issues can be better spent improving other parts of the stack.

It might be a good idea to instead promote usage of something like [`isomorphic-fetch`](https://www.npmjs.com/package/isomorphic-fetch) or [`got`](https://www.npmjs.com/package/got). I'd be happy to submit a pull request for either provided interest.

Also recommended from the blog post: [Axios](https://github.com/mzabriskie/axios).

**Comment by skyrpex** [comment]
I'm astounded all of the choices out there. I really liked the middleware looking interceptors of vue-resource.

**Comment by knpwrs** [comment]
Axios is supposed to have a very similar API. Looks like it supports middleware-style interceptors as well.

**Comment by petervmeijgaard** [comment]
What is your opinion about sticking with [pagekit/vue-resource](https://github.com/pagekit/vue-resource)?
I will take a look at Axios tomorrow 😄

**Comment by skyrpex** [comment]
> Axios is supposed to have a very similar API. Looks like it supports middleware-style interceptors as well.

They are a bit different. You must separate your interceptor in request and response interceptors, and create two callbacks on both in case you want to handle errors.

**Comment by knpwrs** [comment]
I think it would be smarter to promote framework-agnostic solutions and I agree with all the reasoning in the blog post, mainly that there's no need to duplicate effort and ajax is not a core problem that is necessarily appropriate for vue to solve. Look at what happened with angular. You'd have a bunch of libraries, and then `ng-` wrappers for those libraries. Vue is designed to play well with npm, so I'd be in favor of promoting solutions outside of vue.

**Comment by skyrpex** [comment]
Sure, I totally agree with you. I already migrated my newest project to axios with no effort. It's just that it's interceptors are more cumbersome to write.

**Comment by petervmeijgaard** [comment]
Fixed in https://github.com/petervmeijgaard/vue-2.0-boilerplate/commit/e5d8680a5fadd2b917176e3847f14bccd0684e19 😄 
If you've got improvements, feel free to share them!
