### ISSUE TITLE
Windows installation from scratch

### ISSUE THREAD

**Issue by fordarian** [petervmeijgaard/vue-2.0-boilerplate#2]
I was not able to use it in windows from scratch until:

added   `'linebreak-style': ["error", "windows"] ` to .eslintrc.js
and run `npm install babel-runtime --save`

**Comment by petervmeijgaard** [comment]
Hi fordarian, thanks for the headsup! I will Apply the fix tomorrow. I ran into the same issue today. Has to do something with the way Windows handles line endings.

**Comment by petervmeijgaard** [comment]
Fixed in https://github.com/petervmeijgaard/vue-2.0-boilerplate/commit/15f46fdfbdd50cc79668cfef934fc08a58e0a16e
