### ISSUE TITLE
Steps to Deployment?

### ISSUE THREAD

**Issue by devonmather** [petervmeijgaard/vue-2.0-boilerplate#20]
Hey,

Thanks for the time to put together this boiler-plate. The following may seem stupid, but what are the steps to deploy this to a server? I've looked around a bit and this step seems to be oft-neglected on the web. I was hoping that everything would compile down to HTML, JS and CSS, and it wouldn't need node on the server to run, but I think I'm mistaken?

Regards,
Devon Mather

**Comment by vertoo** [comment]
You must have any HTTP server. Probably you have Apache2 on hosting.

You don't need send any files from node_modules/, src/, hidden files, package.json, README.md.

How deploy? Use your own method, ftp, git... You have free choice.

**Comment by devonmather** [comment]
Thanks for the quick reply! I think I figured it out, in case anyone else is new to npm like me.

- Navigate to location of app
- Enter **npm run build** in the terminal
- Navigate to app/dist
- Upload the containing files in dist to server via ftp/git etc.

**Comment by encryptedtouhid** [comment]
> I think I figured it out, in case anyone else is new to npm like me.
> 
> * Navigate to location of app
> * Enter **npm run build** in the terminal
> * Navigate to app/dist
> * Upload the containing files in dist to server via ftp/git etc.
> 
> Let me know if any of that is incorrect.

and after this i am getting blank screen
