### ISSUE TITLE
Computed properties within page javascript

### ISSUE THREAD

**Issue by PHILLIPS71** [petervmeijgaard/vue-2.0-boilerplate#23]
I'm wanting to retrieve a users data from my external API when someone views a profile page by grabbing the users ID within the route params. The issue is when the server responds I can't just go this.user = response since this is undefined as it's not in a Vue file. I'm not sure if I'm using the boilerplate correctly in this case.

Am I going to need to setup an entire new vuex state to hold the data I'm trying to access then retrieve it from there? I just don't understand on how you could achieve this in the way the boilerplate is setup as all my users data is not being updated after the response and continues to be null.

```
import Vue from 'vue';

let user = null;

export default {
  data() {
    return {
      user,
    };
  },
  computed: {
    user: () => {
      return user;
    }
  },
  created: () => {
    Vue.$http.get(`/users/${Vue.router.app._route.params.id}`)
      .then((response) => {
        user = response.data;
      });
  },
  components: {
    VLayout: require('layouts/default/default.vue'),
    VPanel: require('components/panel/panel.vue'),
  }
};
```

**Comment by petervmeijgaard** [comment]
You are using computed properties wrong. Perhaps this will do the trick:
```JavaScript
import Vue from 'vue';

export default {
  data() {
    return {
      user : null,
    };
  },
  created() {
    Vue.$http.get(`/users/${this.$route.params.id}`)
      .then((response) => {
        this.user = response.data;
      });
  },
  components: {
    VLayout: require('layouts/default/default.vue'),
    VPanel: require('components/panel/panel.vue'),
  }
};
```

You can also use Vuex to store the user in the state, but that's up to you. I hope that this will work.
Keep in mind that you are updating the `user`-variable which is declared outside of the scope of Vue, which means that this won't trigger the observers.

**Comment by petervmeijgaard** [comment]
Also, keep in mind that you'll need to update the data when you visit a different user page:
http://router.vuejs.org/en/essentials/dynamic-matching.html#reacting-to-params-changes

```JavaScript
import Vue from 'vue';

export default {
  data() {
    return {
      user : null,
    };
  },
  watch: {
    '$route' (to, from) {
      this.fetchUser();
    }
  },
  created() {
    this.fetchUser();
  },
  methods: {
    fetchUser() {
      Vue.$http.get(`/users/${this.$route.params.id}`)
        .then((response) => {
          this.user = response.data;
        });
    }
  },
  components: {
    VLayout: require('layouts/default/default.vue'),
    VPanel: require('components/panel/panel.vue'),
  }
};
```

**Comment by PHILLIPS71** [comment]
Ah okay, I see where I've gone wrong! I also didn't realise that I need to reference the user from the index.html page with the this tag to gain access to the user instead of user.name doing this has solved all my issues where the user was somehow null. Thank you so much for you're help much appreciated!
