### ISSUE TITLE
bind is not a function when vue-i18n in v4.x

### ISSUE THREAD

**Issue by CocaCola183** [petervmeijgaard/vue-2.0-boilerplate#25]
Run `npm run dev` and got error: `bind is not a function`

Update package.json from `vue-i18n": "^4.x` to `vue-i18n": "^5.0.0` fix it

**Comment by petervmeijgaard** [comment]
Thanks for creating an issue!

It's fixed in commit https://github.com/petervmeijgaard/vue-2.0-boilerplate/commit/8355f2a224fbf1aeaaae41359ce3ee157c87abf8

😄
