### ISSUE TITLE
Issue with npm run build

### ISSUE THREAD

**Issue by mohinlakdawala** [petervmeijgaard/vue-2.0-boilerplate#28]
Hi,

Running `npm run build` gives the below error:

```
ERROR in static/js/app.ad81c56779b474d07f40.js from UglifyJs
Unexpected token punc «)», expected punc «(» [./src/bootstrap.js:27,2][static/js/app.ad81c56779b474d07f40.js:142,6]
```
The error is from UglifyJS plugin which doesn't support ES6 code yet (unless using the harmony branch, which is still in development)

Is this because the code is not getting transpiled to ES5 correctly? 

Opening the production version in IE11 gives the same error in console and the site doesn't load.

Please can you have a look?

Thanks in advance.

**Comment by petervmeijgaard** [comment]
Hmm. When I try to run `npm run build` on a fresh installation, it's working on my end.
When I run:
 - `rm -rf node_modules`
 - `yarn`
 - `yarn run build`

Or
 - `rm -rf node_modules`
 - `npm install`
 - `npm run build`

It's both working...

What version of Node, NPM and/or Yarn are you using?
On what OS does the error occur?

**Comment by zloadmin** [comment]
I have some problem

```
ERROR in static/js/app.94ccd00964ceca0ecb7c.js from UglifyJs
Unexpected token punc «)», expected punc «(» [./src/bootstrap.js:27,2][static/js/app.94ccd00964ceca0ecb7c.js:160,6]
```

Remove node_modules folder didnt help. 
I use npm 3.10.10 and node v6.10.0

**Comment by zloadmin** [comment]
1 Add "es2015" in .babelrc 
from
```
"presets": [
	"stage-2"
],
```
to
```
"presets": [
	"stage-2", "es2015"
],
```
2 install packages
`npm install babel-cli babel-preset-es2015`
3 build again
`npm run build`

**Comment by petervmeijgaard** [comment]
Thanks! I'll take a look at it when I got time :)

**Comment by petervmeijgaard** [comment]
Alright, I've applied the fix @zloadmin suggested.
If someone can test this using Internet Explorer, that would be great 😄 
You can checkout the `develop`-branch to check if it's working.

**Comment by shuaibird** [comment]
The `babel-preset-es2015` should be used for vue-loader to transpile ES6 syntax into ES5
By the way, I recommend use the `babel-preset-stage-0` rather than the `babel-preset-stage-2` for implementing more ES6 sweet syntax

**Comment by petervmeijgaard** [comment]
@shuaibird Thanks for recommending the `stage-0` preset, but I'll stick with the `stage-2` preset for now. The `stage-0` is a bit too bleeding edge for me and a lot of features won't make it to `stage-2`. Thanks for the headsup by the way!
