### ISSUE TITLE
Opening index.html over file:// won't work.

### ISSUE THREAD

**Issue by zloadmin** [petervmeijgaard/vue-2.0-boilerplate#30]
When i build scrips i get this error

  Tip: built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.

I think it's script can't write in index.html

**Comment by petervmeijgaard** [comment]
Can you please change the title to something a bit more readable? 😄

**Comment by petervmeijgaard** [comment]
This is not an error. It basically says that you need to serve the production files using a webserver.
When you open the file directly in your browser, it simply won't work.
