### ISSUE TITLE
Windows Scaffolding issue

### ISSUE THREAD

**Issue by fordarian** [petervmeijgaard/vue-2.0-boilerplate#4]
Hi! Scaffolding in windows is kinda broken for me.

1) By default it drops:

> `E:\01 Coding\order\task\create-component\task.js:3
> class CreateComponent {
> ^^^^^
> 
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet sup
> ported outside strict mode
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:441:10)
>     at startup (node.js:139:18)
>     at node.js:968:3
> 
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "create" "page" "agents"
> npm ERR! node v4.4.7
> npm ERR! npm  v2.15.8
> npm ERR! code ELIFECYCLE
> npm ERR! vue-2-boilerplate@0.0.0 create: `node task/create-component/task.js "page" "agents"`
> npm ERR! Exit status 1

But this can be fixed by adding `"use strict";` to the top of the  `\task\create-component\task.js`

2) Then it exits with:

> E:\01 Coding\order>npm run create page agents
> 
> > vue-2-boilerplate@0.0.0 create E:\01 Coding\order
> > node task/create-component/task.js "page" "agents"
> 
> Start create-component task
> Create main component: agents
> fs.js:794
>   return binding.mkdir(pathModule._makeLong(path),
>                  ^
> 
> Error: ENOENT: no such file or directory, mkdir 'E:\src\app\pages\agents'
>     at Error (native)
>     at Object.fs.mkdirSync (fs.js:794:18)
>     at CreateComponent.createMain (E:\01 Coding\order\task\create-component\task
> .js:92:8)
>     at CreateComponent.init (E:\01 Coding\order\task\create-component\task.js:71
> :10)
>     at new CreateComponent (E:\01 Coding\order\task\create-component\task.js:51:
> 10)
>     at Object.<anonymous> (E:\01 Coding\order\task\create-component\task.js:143:
> 1)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
> 
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "create" "page" "agents"
> npm ERR! node v4.4.7
> npm ERR! npm  v2.15.8
> npm ERR! code ELIFECYCLE
> npm ERR! vue-2-boilerplate@0.0.0 create: `node task/create-component/task.js "page" "agents"`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the vue-2-boilerplate@0.0.0 create script 'node task/create-component/task.js "page" "agents"'.
> npm ERR! This is most likely a problem with the vue-2-boilerplate package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node task/create-component/task.js "page" "agents"
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs vue-2-boilerplate
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!
> npm ERR!     npm owner ls vue-2-boilerplate
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     E:\01 Coding\order\npm-debug.log
> 

It looks like the app path is not recognized correctly (mkdir 'E:\src\app\pages\agents', and my app full path is "E:\01 Coding\order\")

Debug log:
[npm-debug.log.txt](https://github.com/petervmeijgaard/vue-2.0-boilerplate/files/432353/npm-debug.log.txt)

**Comment by petervmeijgaard** [comment]
Hi! I'm currently on vacation! Will check next tuesday! The scaffolding is still unstable and need to be refactored. For now, create the files manually.

**Comment by petervmeijgaard** [comment]
Btw, update to the latest version of Node instead of 4.4.7

**Comment by fordarian** [comment]
> Btw, update to the latest version of Node instead of 4.4.7
Hey, that was almost LTS (4.5) :)

Updated to node 6.4.0 and nmp 3.10.3 - still dont work with the same error.

**Comment by petervmeijgaard** [comment]
I have created a standalone CLI package:
https://github.com/vivid-web/lucevi

Still in development, but you can try it by using `npm i -g lucevi`.
Use `lucevi make:component my-component` or `lucevi make:layout my-layout`.
Page support will be added soon!
