### ISSUE TITLE
Please Update

### ISSUE THREAD

**Issue by paolog22** [petervmeijgaard/vue-2.0-boilerplate#42]
this is awesome hope you update soon thanks

**Comment by petervmeijgaard** [comment]
What do you want me to update? Do you want me to bump the version of the Vue ecosystem?

**Comment by paolog22** [comment]
yes sir that would be very awesome.. thanks :)

**Comment by paolog22** [comment]
and also vue-router-sync is not support in vue2.0 sad :(

**Comment by petervmeijgaard** [comment]
Fixed in https://github.com/petervmeijgaard/vue-2.0-boilerplate/commit/1644841fc5373c456ae4d3dd4d79cbc6c8769ad6 😄

**Comment by petervmeijgaard** [comment]
Also, `vue-router-sync` is working correctly at my end...
