### ISSUE TITLE
Help. how to use the proxies

### ISSUE THREAD

**Issue by paolog22** [petervmeijgaard/vue-2.0-boilerplate#44]
i import the authproxy then called authproxy.login() 
log error is auth.login is not a function..

thanks

**Comment by paolog22** [comment]
new authproxy().login()

please close this sorry my bad :)

**Comment by petervmeijgaard** [comment]
No problem at all! I agree that it was a bit vague how to use the proxies. I hope that it is fixed now in this [commit](https://github.com/petervmeijgaard/vue-2.0-boilerplate/pull/45/commits/fe6aa2c83541142b4721cfd753a62afa0ee97dfd)
