### ISSUE TITLE
Integrate in a laravel app

### ISSUE THREAD

**Issue by itsazzad** [petervmeijgaard/vue-2.0-boilerplate#7]
Can I integrate this in https://github.com/petervmeijgaard/jwt-example ?
If yes then have you any suggestion?

**Comment by itsazzad** [comment]
Yes! Just I could integrate.

**Comment by petervmeijgaard** [comment]
Yes sir! You can easily integrate the boilerplate in a Laravel application. The only thing you need to do is to update the configuration to your settings, as you can see here.
https://github.com/petervmeijgaard/jwt-example/blob/master/resources/frontend/config/index.js
