### ISSUE TITLE
just read the code, a fucking greate one!!

### ISSUE THREAD

**Issue by lymanlai** [petervmeijgaard/vue-2.0-boilerplate#9]
u can close this issue at any time, just want to tell u I like this boilerplate!!

for before I have been spend a lot of time on writing vue/vuex 1.0 app!

now trying to move in to 2.0!

HOLA!!!

**Comment by petervmeijgaard** [comment]
Thanks 😄 !
If you've got improvements, feel free to create an issue or send me a PM 👍

**Comment by pelletiermaxime** [comment]
Same for me! I just used this boilerplate to do a medium sized app and it really helped me keep my code clean and saved me a lot of time I would have spent configuring stuff. Plus it helper me move to 2.0 =).
Thanks!

**Comment by harrysbaraini** [comment]
Yeah. I have done some tweaks to this boilerplate, to something a bit more modular (think of modules which register pages, routes, etc), then in bootstrap, you just pass a list of available modules. But this boilerplate is great!!
